import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import BouncingBall from './components/bouncingBall'
import CasestudiesDetails from './components/caseStudiesDetails'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CasestudiesDetails /> */}
      <Navbar />
      {/* <BouncingBall /> */}
      {children}</body>
    </html>
  )
}
